### ISSUE TITLE
DEACTIVATE of content not supported

### ISSUE THREAD

**Issue by ankur-mittal** [nateyolles/aem-akamai-replication-agent#1]
While testing the agent, I realized that only Activate and Test Replication actions are supported, which is fine. But there are good chances that pages get deleted from AEM and then have to be deleted from Akamai and Dispatcher in real time. So Wanted to check if there is any specific reason, for which you did not add Deactivate action.

**Comment by nateyolles** [comment]
Thank you for pointing that out. I will update the code.

**Comment by nateyolles** [comment]
Purge/invalidation request sent to Akamai on ReplicationActionType.DEACTIVATE.
